---

- name: install auditd package | package-08
  package:
    name: 'auditd'
    state: 'present'

- name: configure auditd | package-08
  template:
    src: 'auditd.conf.j2'
    dest: '/etc/audit/auditd.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'
